# Generated by Django 5.2.1 on 2025-07-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('file', models.FileField(upload_to='uploads/')),
                ('phone', models.CharField(max_length=10)),
                ('feedback', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
