# Generated by Django 5.2.7 on 2025-10-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Name',
            new_name='name',
        ),
    ]
