# Generated by Django 5.2.7 on 2025-10-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_address_table_address_rename_age_table_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='age',
            field=models.IntegerField(),
        ),
    ]
